### ISSUE TITLE
Does not run on android

### ISSUE THREAD

**Issue by sunilguptasg** [dartoos-dev/well_formed#62]
Get this error when target is a real android tablet. Note Flutter is on the latest version (2.8). Code works on Chrome.

E/AndroidRuntime(15596): FATAL EXCEPTION: main
E/AndroidRuntime(15596): Process: dev.dartoos.example, PID: 15596
E/AndroidRuntime(15596): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{dev.dartoos.example/dev.dartoos.example.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "dev.dartoos.example.MainActivity" on path: DexPathList[[zip file "/data/app/~~fBpJgpDsPNUJZ5jkTF0T0w==/dev.dartoos.example-qBLtNvTyZxDc87lY2KhO-Q==/base.apk"],nativeLibraryDirectories=[/data/app/~~fBpJgpDsPNUJZ5jkTF0T0w==/dev.dartoos.example-qBLtNvTyZxDc87lY2KhO-Q==/lib/arm64, /data/app/~~fBpJgpDsPNUJZ5jkTF0T0w==/dev.dartoos.example-qBLtNvTyZxDc87lY2KhO-Q==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]

**Comment by rafamizes** [comment]
I'll fix it and let you know.

**Comment by rafamizes** [comment]
@sunilguptasg 
It seems that the issue have been solved; the demo app ran perfectly on my Android phone. Please, update the well_formed package to version 0.4.1 and try running the demo application again on your Android Tablet.

**Comment by sunilguptasg** [comment]
Thanks, works now!
